name: quizzy_rewards
description: A quiz app where users earn coins and redeem for real money.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # UI & State
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.4
  intl: ^0.19.0

  # Ads
  google_mobile_ads: ^5.1.0

  # Others
  flutter_local_notifications: ^17.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"